### ISSUE TITLE
Strange quote is raising an error in IE

### ISSUE THREAD

**Issue by ghost** [sukima/ember-cli-select-picker#38]
Hi,

the quotes around click in 

``` javascript
setupDom: Ember.on('didInsertElement', function() {
    $(document).on(
      `click.${this.get('elementId')}`,
      Ember.run.bind(this, this.hideDropdownMenu)
    );
  }),
```

(in app/component/select-picker,js) raise an error in IE. Chrome and Firefox work fine. Just replacing it with a single quote works as expected.

Kind regards
Joscha

**Comment by sukima** [comment]
What is the output of Bable? Ember-CLI is supposed to transpile the ES6 to ES5. How did the back ticks get into the code that IE, FF, or Chrome executes?

**Comment by ghost** [comment]
You're so right of course. Babel was messing up stuff (reinstalled via npm and everything works fine). Thanks for the quick answer.

**Comment by sukima** [comment]
Glad it helped.
