### ISSUE TITLE
Cannot view what is selected when disabled

### ISSUE THREAD

**Issue by Panman82** [sukima/ember-cli-select-picker#43]
I've noticed a UX issue when you set the select-picker to disabled. In this case, the button for the select-picker is disabled, so you cannot open the select-picker "drop-down". Therefore, you can't see what is selected specifically, just "_n_ Items Selected". Could it be changed so that you _can_ click the select-picker button but not edit what is selected?

**Comment by sukima** [comment]
Technically it _can_ be done. I'll mark this as a feature.

Anyone wana take up the challenge?

**Comment by sukima** [comment]
Fixed in 2.3.0
