### ISSUE TITLE
keyboard-select-picker traps up/down arrows for entire view

### ISSUE THREAD

**Issue by sukima** [sukima/ember-cli-select-picker#45]
The keyboard-select-picker traps the <kbd>Up</kbd>, <kbd>Down</kbd>, and <kbd>Return</kbd> keys to manage selecting with the keyboard. However this is not isolated to just the select picker and actually traps the entire page preventing those keys from doing their normal actions (for example in a `textarea`).

**Comment by sweco-secfha** [comment]
I just submitted a PR for this: https://github.com/sukima/ember-cli-select-picker/pull/46

**Comment by sukima** [comment]
Fixed in 2.3.0
