### ISSUE TITLE
Is keyboardShortcuts "tab" and "shift+tab" really necessary?

### ISSUE THREAD

**Issue by sweco-secfha** [sukima/ember-cli-select-picker#47]
For me "tab" and "shift+tab" is used to move through inputs in a form.
`keyboard-select-picker` forces me to use the mouse to move along as i get trapped there.

**Comment by sukima** [comment]
On regular `select-picker` or `keyboard-select-picker`?

**Comment by sweco-secfha** [comment]
Sorry, i'm talking about `keyboard-select-picker`

**Comment by sukima** [comment]
Perhaps it would benefit to move the component logic (JavaScript) into a mixin so that users can override / mix and match features. I'll look into it when I get to it or a someone comes up with a solution before that.

**Comment by sweco-secfha** [comment]
Can you elaborate that? How would it work?
If I get som free time I would be happy to look into it.

**Comment by sukima** [comment]
The comment about the mixin was in reaction to how to allow a user to define their own keyboard shortcuts. This could be accomplished using mixins.

I was about to elaborate on what I meant when I realized that this topic a mute topic. I want to remove the `ember-keyboard-shortcuts` dependency all together. If I rewrite the `keyboard-select-picker` to respond to actions and attach those actions to jQuery `keyup` events then jQuery will handle the browser inconsistencies with keyboard events and the logic in this addon become simplified and generic.

We have this on our radar at work so I think it will happen soon.

**Comment by sukima** [comment]
Fixed in 2.3.0
