### ISSUE TITLE
Fix tests, setup Travis CI

### ISSUE THREAD

**Issue by johnnyshields** [sukima/ember-cli-select-picker#5]
Currently 6 out of 7 tests passing.

**Comment by sukima** [comment]
I haven't done _any_ testing. I'm surprised there are 7 tests! Interested in doing more?

**Comment by johnnyshields** [comment]
I'll get one of my teammates on the job soon.

**Comment by johnnyshields** [comment]
Fixed by PR #9, raising separate issue for Travis
