### ISSUE TITLE
long lists and data-size

### ISSUE THREAD

**Issue by haldiggs** [sukima/ember-cli-select-picker#59]
the bootstrap version allows the data-size attribute to limit the list size... it makes it scroll.

http://silviomoreto.github.io/bootstrap-select/examples/#menu-size

is there a way to make this work with this component?

**Comment by sukima** [comment]
Maybe. Off the top of my head as the component performs a resize tap into the event . Calculate the height of the largest list item and set the height of the div to that times the number of items and set the div overflow to scroll.

That said it seems like a lot of work. How does bootstrap-ember handle it?

There is also better alternatives out there like [ember-power-select](http://www.ember-power-select.com/cookbook/bootstrap-theme) and the [ember-bootstrap](https://kaliber5.github.io/ember-bootstrap/) which has a dropdown component that could be used.
